# Generated by Django 3.0.3 on 2020-05-11 23:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='accounts/default/default-profile-pic.png', null=True, upload_to=accounts.models.upload_location),
        ),
    ]
