# Generated by Django 3.0.3 on 2020-05-17 17:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200512_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='taha', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='sidkom', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='accounts/default/default-profile-pic.png', upload_to=accounts.models.upload_location),
        ),
    ]
