# Generated by Django 3.0.3 on 2020-05-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='slug',
        ),
    ]
